emojis:
  - keyword: "pride"
    emoji: "<bold><color:#E40303>P<color:#FF8C00>R<color:#FFED00>I<color:#008026>D<color:#004DFF>E<color:#750787>❤</color></bold>"
  - keyword: "lol"
    emoji: "<red><bold>LOL</bold></red>"
  - keyword: "dundigundi"
    emoji: "<bold><color:#ffaaff>dundigundi</color></bold>"
  - keyword: "shrug"
    emoji: "<yellow>¯\\_(ツ)_/¯</yellow>"
  - keyword: "hype"
    emoji: "<bold><gradient:green:blue:yellow>HYPE!</gradient></bold>"
  - keyword: "gg"
    emoji: "<gradient:#FF4500:#FFD700><bold>GG</bold></gradient>"
  - keyword: "rip"
    emoji: "<gray><italic><bold>R.I.P</bold></italic></gray>"
  - keyword: "facepalm"
    emoji: "<bold><red>*facepalm*</red></bold>"
  - keyword: "bruh"
    emoji: "<dark_gray><italic><bold>BRUH...</bold></italic></dark_gray>"
  - keyword: "clap"
    emoji: "<bold><gradient:yellow:green>CLAP!</gradient></bold>"
  - keyword: "boom"
    emoji: "<gradient:red:gold><bold>BOOM!</bold></gradient>"
  - keyword: "wow"
    emoji: "<bold><gradient:aqua:blue:dark_purple>WOW!</gradient></bold>"
  - keyword: "nope"
    emoji: "<red><italic><bold>NOPE!</bold></italic></red>"
  - keyword: "party"
    emoji: "<gradient:yellow:blue><bold><italic>PARTY!</italic></bold></gradient>"
  - keyword: "oof"
    emoji: "<dark_red><bold>OOF</bold></dark_red>"
  - keyword: "smile"
    emoji: "<gold>:D</gold>"
  - keyword: "yes"
    emoji: "<green><bold>✔ YES!</bold></green>"
  - keyword: "no"
    emoji: "<red><bold>✖ NO!</bold></red>"
  - keyword: "cool"
    emoji: "<aqua><bold>B)</bold></aqua>"
  - keyword: "flex"
    emoji: "<yellow><bold>FLEX!</bold></yellow>"
  - keyword: "hello"
    emoji: "<bold><gradient:light_purple:gold>Hello!</gradient></bold>"
  - keyword: "bye"
    emoji: "<italic><dark_purple>Goodbye!</dark_purple></italic>"
  - keyword: "sorry"
    emoji: "<italic><gray><bold>Sorry...</bold></gray></italic>"
  - keyword: "thanks"
    emoji: "<gradient:gold:green><bold>Thanks!</bold></gradient>"
  - keyword: "welcome"
    emoji: "<bold><gradient:green:light_purple>Welcome!</gradient></bold>"
  - keyword: "pls"
    emoji: "<italic><light_purple>Pls?</light_purple></italic>"
  - keyword: "ok"
    emoji: "<bold><gold>OK!</gold></bold>"
  - keyword: "why"
    emoji: "<italic><red>Why?</red></italic>"
  - keyword: "uh"
    emoji: "<dark_gray><italic>Uh...</italic></dark_gray>"
